### ISSUE TITLE
DSGetJobInfo not working

### ISSUE THREAD

**Issue by Thurmy34** [reijnnn/IBM-DataStage-API#1]
Hello
I tried the example number 4 and it doesn't work.
I have this
Getting the last start time of the job
Getting the log from  0
Runtime error: exception: access violation reading 0x00000000
Deblocking the job
Closing the job
Closing the project

It appears that the DSGetJobInfo function doesn't return anything.
I'm on windows 2010 with Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Thank you

**Comment by reijnnn** [comment]
Hello
1. What are you using? Parallel job or sequence job? 
2. This object already been compiled?
3. Another examples (1, 2, 3) work correctly?

**Comment by Thurmy34** [comment]
Hello

What are you using? Parallel job or sequence job?
I tried two jobs one server and one parallel

This object already been compiled?
Yes they are

Another examples (1, 2, 3) work correctly?
The example 1 works fine , i'll try the other two and keep you posted.
Thank Yoy

**Comment by Thurmy34** [comment]
Hello
The example 2 is ok
I tried the get param example and it doesn't work.
Getting an information about the job

DSJ_PARAMLIST = []
My job have parameters .

I tried the run jobexample and it doesn't work.
Getting an information about the job
DSJ_JOBSTATUS = 0
DSJ_PARAMLIST = []
DSJ_JOBPID = 0
DSJ_JOBSTARTTIMESTAMP = 0
DSJ_JOBLASTTIMESTAMP = 0
DSJ_JOBRESTARTABLE = 0
Thank you

**Comment by reijnnn** [comment]
Hello
What kind of user do you use?
You need an OS user of DataStage server, not user for Director/Designer

**Comment by Thurmy34** [comment]
Hello
I'm not sure what an operating system user is but i swicht to the credential user .
I now have this error 
Setting the parameters to connect to DataStage server
Loading the project BCPDEV
Runtime error: Can't open the project BCPDEV: [ERROR.DSAPI]: [DSOpenProject]: -1010

The user i used doesn't exist in Datastage.
Thank you

**Comment by reijnnn** [comment]
Open [IBM InfoSphere Information Server Web console](https://www.ibm.com/support/knowledgecenter/en/SSZJPZ_11.7.0/com.ibm.swg.im.iis.found.moz.wc.admin.doc/topics/t_wc_creating_users.html) 
Find your user 
Add role "DataStage and QualityStage Developer"

**Comment by Thurmy34** [comment]
Hello
I'm back to square one
Setting the parameters to connect to DataStage server
Loading the project XXX
<ibm_datastage_api.LP_DSPROJECT object at 0x00A49580>
Loading the job YYY
<ibm_datastage_api.LP_DSJOB object at 0x00A49990>
-- The DSGETINFO job structure is "empty" : ---
Getting the last start time of the job
Getting the log from  0
Runtime error: exception: access violation reading 0x00000000
Deblocking the job
Closing the job
Closing the project
Exit.

**Comment by reijnnn** [comment]
Did you add this user role?

**Comment by Thurmy34** [comment]
yes I did

**Comment by reijnnn** [comment]
Can you show your config.py?
What version of DS do you have?

**Comment by Thurmy34** [comment]
Here is my config.py
# IBM DataStage Server's parameters
DS_DOMAIN_NAME = 'XXXX:9443'
DS_USER_NAME   = 'USR1'
DS_PASSWORD    = 'USR1'
DS_SERVER      = 'XXX'

# ProjectJob
DS_PROJECT  = 'XXXDEV'
DS_JOB_NAME = 'Jx_MonJOB'

# Full path to API library (vmdsapi.dll or libvmdsapi.so)
API_LIB_FILE = 'C:/IBM/InformationServer11.5/Clients/Classic/vmdsapi.dll'

I use DST 11.5 fp1

Thank You

**Comment by reijnnn** [comment]
Set
DS_DOMAIN_NAME = ''

**Comment by Thurmy34** [comment]
with
DS_DOMAIN_NAME = ''

Loading the project XXX
Runtime error: Can't open the project XXX: [ERROR.DSAPI]: [DSOpenProject]: 80011
Exit.

Thanks

**Comment by reijnnn** [comment]
I tried another user and got the same error.
As I said above, you need an OS user.

1. Create OS user and set user password
`useradd -d /home/<user> -g dstage -m <user>`
`passwd <user>`
2. Create a DS user in the [IBM InfoSphere Information Server Web console](https://www.ibm.com/support/knowledgecenter/en/SSZJPZ_11.7.0/com.ibm.swg.im.iis.found.moz.wc.admin.doc/topics/t_wc_creating_users.html) with the <strong>same</strong> name
3. Perform [mapping user credentials](https://www.ibm.com/support/knowledgecenter/en/SSZJPZ_11.7.0/com.ibm.swg.im.iis.found.moz.wc.admin.doc/topics/wsisinst_config_user_mappings.html) with OS user
4. Configure your project in the Administrator Client (Projects->Properties->Permissions->Add user)

You can skip 1

**Comment by Thurmy34** [comment]
Hi
The OS user has to be a local one ?
The DS user can't be in a group ?
Because when i tested with or credential user i perform the actions that you recommend.
Anyway i'll test and keep you posted.
Thank

**Comment by reijnnn** [comment]
Hi
1) You must create a OS user on the DS server or you can use an existing one
2) My DS user has groups and the developer role 

It is hard to help blindly

**Comment by Thurmy34** [comment]
Hi
I understand an i apreciate your help.
Unfortunately it still doesn't work.
My Ds serveur is on windows 2012 R2 ... 
Thank you

**Comment by reijnnn** [comment]
I don't have any experience with DS windows server.
Do you have [dsadm](https://www.ibm.com/support/knowledgecenter/en/SSZJPZ_11.7.0/com.ibm.swg.im.iis.found.admin.common.doc/topics/admsec_engine_security_overview.html) user on OS level?

**Comment by Thurmy34** [comment]
Maybe we can try to solve my other issue
Because my target is to user your API on Redhat with DS 11.7

**Comment by reijnnn** [comment]
Do you have dsadm user on OS level on Redhat?

**Comment by Thurmy34** [comment]
yes i do

**Comment by reijnnn** [comment]
Try to set
DS_USER_NAME   = 'dsadm'
DS_PASSWORD    = `this OS user password`

**Comment by Thurmy34** [comment]
Hello Again
A short summary
When python is on windows
I can connect to DST 11.5 windows.
I can't connect to DST 11.7 redhat.
 
When python is on redhat
I can't connect to DST 11.5 windows.
I can't connect to DST 11.7 redhat.

I 'm using the same config.py on windows and redhat (except for API_LIB_FILE)
Thank you

**Comment by reijnnn** [comment]
What errors do you have? Is it still 80011?
Try to use `dsadm`?

Python on windows - it's your PC?
Python on redhat - it's a remote server with DS Engine?

You try to connect from a single PC to 11.5 and 11.7? Both clients are installed?
When you try to connect to 11.7 you change API_LIB_FILE?

**Comment by Thurmy34** [comment]
What errors do you have? Is it still 80011? --> yes
Try to use dsadm? --> yes

Python on windows - it's your PC? --> yes 
Python on redhat - it's a remote server with DS Engine? --> yes

**Comment by reijnnn** [comment]
You try to connect from a single PC to 11.5 and 11.7. Both clients are installed?
When you try to connect to 11.7 you change API_LIB_FILE?

Did you try to connect to redhat through ssh using `dsadm` credential?

**Comment by Thurmy34** [comment]
Hi
I'm sorry for the late answer i was out of the office yesterday.
You try to connect from a single PC to 11.5 and 11.7. Both clients are installed? --> No i have just the 11.5.
When you try to connect to 11.7 you change API_LIB_FILE? --> No

Did you try to connect to redhat through ssh using dsadm credential? --> Yes and it works but dsadm doesn't exists as a DST user.
Thank you

**Comment by reijnnn** [comment]
Hi
When you run a task in DS Designer, the logs contain information about "Environment variable settings".
What user is used there?
USER=dsadm?

Do Services tier and Engine tier locate on the same server/ip?

**Comment by Thurmy34** [comment]
Hi
USER=dsadm --> isn't dsadm but it's our credential/OS user.
Do Services tier and Engine tier locate on the same server/ip? --> yes 
Thank You

**Comment by reijnnn** [comment]
Hi
Did you try to connect to API using your OS user?

**Comment by Thurmy34** [comment]
Hi 
Yes i did and i had the 80011 error.
Thank you

**Comment by reijnnn** [comment]
Did you try to connect to redhat through ssh using this OS user credential?

**Comment by Thurmy34** [comment]
Yes i did and it works

**Comment by reijnnn** [comment]
I tried to connect to different servers and I didn't have this problem. I don't know what else can help you.

**Comment by Thurmy34** [comment]
Hello
Does you Os user exists as a DST user ?
On redhat the  DST users come from the AD.
Thanks

**Comment by reijnnn** [comment]
My OS user doesn't exist as DS user.
The OS user has a `dstage` group

**Comment by reijnnn** [comment]
Hi
Try it on redhat with your OS user:
`cd ../IBM/InformationServer/Server/DSEngine/bin/`
`./dsjob -logdetail your_project_name your_job_name`

[Help link1](https://www.ibm.com/support/pages/apar/JR55767)
[Help link2](https://www.ibm.com/support/pages/trying-connect-datastage-clients-gives-error-80011)
[Help link3](https://www.ibm.com/support/knowledgecenter/SSZJPZ_8.5.0/com.ibm.swg.im.iis.found.admin.common.doc/topics/admsec_engine_security_with_shared_reg.html)

**Comment by Thurmy34** [comment]
Hi
It works with this command
/opt/IBM/InformationServer/Server/DSEngine/bin/dsjob -domain NONE -server myserver -user dsadm -password xxxx -logdetail MyProject Myjob

**Comment by reijnnn** [comment]
1) What error do you have if you exec my command?
2) Try to exec your command from your local client to redhat server. Do you have error in this case?
`cd ..\IBM\InformationServer\Clients\Classic`
`dsjob -domain NONE -server myserver -user dsadm -password xxxx -logdetail MyProject Myjob`

**Comment by Thurmy34** [comment]
Hi
1
I didn't understand that i don't need to specify the user that's why i added domain server etc
The command works on the redhat server when connected with the OS user.
2
The command works on my pc.

Thanks

**Comment by reijnnn** [comment]
Hi, Thurmy34
I think I've found the solution to your problem.

Try use
`DS_DOMAIN_NAME = 'HOST_NAME:PORT_IIS_CONSOLE'`
`DS_SERVER      = 'HOST_NAME:PORT_ENGINE'`

and user credential for Disgner/Director
