### ISSUE TITLE
Connection Impossible

### ISSUE THREAD

**Issue by Thurmy34** [reijnnn/IBM-DataStage-API#2]
Hi 
On redhat i can't connect to datastage
[DSGetProjectList]: 80011
Python 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Thank you

**Comment by reijnnn** [comment]
Hello

80011 - Incorrect system name or invalid user name or password provided
[Error codes](https://www.ibm.com/support/knowledgecenter/en/SSZJPZ_11.7.0/com.ibm.swg.im.iis.ds.cliapi.ref.doc/topics/r_dsvjbref_Error_Codes.html)

**Comment by Thurmy34** [comment]
Hello
I'm sorry i wasn't clear enough.
I know what 80011 means, but i don't understand why i got this error.
In fact with the same config file i can connect on windows but not on redhat.
Thank you
