### ISSUE TITLE
DLL setup not working

### ISSUE THREAD

**Issue by brian316** [reijnnn/IBM-DataStage-API#3]
I set up the `config.py` as follows
API_LIB_FILE = '../../IBM/InformationServer/Clients/Classic/vmdsapi.dll'

I verified the location of windows DLL

Error:
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/3878246/189782765-dc392940-b2d2-4240-948a-592584eea970.png">

**Comment by reijnnn** [comment]
Hello, please check that IBM DataStage and python have the same architecture version (64 or 32)
