### ISSUE TITLE
 Can't open the project XXX : 'code': 81002

### ISSUE THREAD

**Issue by ldmar** [reijnnn/IBM-DataStage-API#4]
HI reijnnn, 

Прежде всего спасибо.

Мне удалось подключиться к Datastage, но при загрузке проекта выдается ошибка.

со следующей ошибкой:
Runtime error: Can't open the project XXX : {'type': 'error', 'func': 'DSOpenProject', 'code': 81002, 'msg': 'Unknown error code'}

Я просмотрел документацию IBM и не смог найти код ошибки API.

Я надеюсь, что вы можете помочь мне с этим.

Добавляю данные, подключаюсь через впн к хосту.

Не знаю, из-за этого ли это.

Спасибо
Лаутаро

**Comment by reijnnn** [comment]
Привет.

Я не встречал ранее подобную ошибку.

Ты запускаешь пример из файла `2_get_project_info.py`?
Работает ли у тебя пример `1_get_projects_list.py`?

Можно попробовать покрутить настройки подключения: hostname заменить на ip адрес, попробовать пользователя с большими привилегиями.

Так же можно попробовать выполнить код находясь во внутренней сети сервера, чтобы исключить проблему связанную с vpn.

**Comment by ldmar** [comment]
Привет.

И все это привело к ошибке.
Когда был завершен проект:
  hproj, err = dsapi.DSOpenProject(DS_PROJECT)
 
Измените хост и выберите IP-адрес, и я снова поймаю ошибку.
Я использую пользователя dsadm, и он выдает ошибку.

Я думаю, что вы можете использовать VPN, но не можете попробовать сделать это из красного, чтобы устранить VPN.

Для другого случая также необходимо подготовить терминальный сервер, чтобы он мог работать.

Спасибо вам за участие в конкурсе.
Попробую изнутри сети и скажу.
